build also creates binaries for linux

diff --git a/tools/build/build b/tools/build/build
--- a/tools/build/build
+++ b/tools/build/build
@@ -1,4 +1,80 @@
 #!/bin/sh
+
+if [ "$EUID" -ne 0 ]
+  then echo "Please run as root"
+  exit
+fi
+#Detect OS and use corresponding package manager for dependencies. I only use three of these distros so maybe others can clean up the code of their main distro
+if [[ -f '/etc/arch-release' ]]; then
+  echo -ne '\n y' | sudo pacman -Sy base-devel git curl
+fi
+if [[ -f '/etc/debian version' ]]; then
+  dpkg --add-architecture i386
+  apt-get update
+  apt-get install -y build-essential git curl lib32z1 pkg-config libssl-dev:i386 libssl-dev
+fi
+if [[ -f '/etc/centos-release' ]] || [[ -f '/etc/fedora-release' ]]; then #DNF should work for both of these
+  sudo dnf --refresh install make automake gcc gcc-c++ kernel-devel git curl
+fi
+if [[ -f '/etc/alpine-release' ]]; then
+  sudo apk add --update alpine-sdk
+fi
+if command -v zypper &> /dev/null
+then
+  zypper install -t pattern devel_basis
+  zypper install -t pattern openssl-devel
+fi
+
+cd binaries
+
+#Install rust if not present
+if ! [ -x "$has_cargo" ]; then
+	echo "Installing rust..."
+	curl https://sh.rustup.rs -sSf | sh -s -- -y
+	. ~/.profile
+fi
+
+#Download/update rust-g repo
+if [ ! -d "rust-g" ]; then
+	echo "Cloning rust-g..."
+	git clone https://github.com/tgstation/rust-g
+	cd rust-g
+	~/.cargo/bin/rustup target add i686-unknown-linux-gnu
+else
+	echo "Fetching rust-g..."
+	cd rust-g
+	git fetch
+	~/.cargo/bin/rustup target add i686-unknown-linux-gnu
+fi
+
+#Compile and move rust-g binary to repo root
+echo "Deploying rust-g..."
+git checkout "$RUST_G_VERSION"
+env PKG_CONFIG_ALLOW_CROSS=1 ~/.cargo/bin/cargo build --release --target=i686-unknown-linux-gnu
+mv target/i686-unknown-linux-gnu/release/librust_g.so ../../../../librust_g.so
+cd ..
+
+#Download/update auxmos repo
+if [ ! -d "auxmos" ]; then
+	echo "Cloning auxmos..."
+	git clone https://github.com/Putnam3145/auxmos
+	cd auxmos
+	~/.cargo/bin/rustup target add i686-unknown-linux-gnu
+else
+	echo "Fetching auxmos..."
+	cd auxmos
+	git fetch
+	~/.cargo/bin/rustup target add i686-unknown-linux-gnu
+fi
+
+#Compile and move auxmos binary to repo root
+echo "Deploying auxmos..."
+git pull origin master #To-do: Replace with version control from dependencies.sh
+env PKG_CONFIG_ALLOW_CROSS=1 ~/.cargo/bin/cargo build --release --target=i686-unknown-linux-gnu
+mv target/i686-unknown-linux-gnu/release/libauxmos.so ../../../../libauxmos.so
+cd ..
+
+#Build TGUI
 set -e
 cd "$(dirname "$0")"
 exec ../bootstrap/node build.js "$@"
